[package]
name = "blocknative-wasi"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["lib", "cdylib"]

[dependencies]
http_req_wasi = "0.10"
serde_json = "1.0"
blocknative-flows = { path = "../blocknative-sdk" }
